# To execute this docker-compose yml file use `docker compose -f docker-compose-restfulbooker.yml up -d`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-restfulbooker.yml down`
version: "3"
services:
  restful-booker:
    image: mwinteringham/restfulbooker
    ports:
      - 3001:3001